### ISSUE TITLE
建议可以打开多个页面。

### ISSUE THREAD

**Issue by jsonMark** [feihua/zero-admin#13]
公司前端模板技术选型，zero-admin因为不能打开多个页面，直接被否了。这个功能很实际。

**Comment by feihua** [comment]
这个antd pro官网没有提供，自己实现起来也麻烦，提供另外一个给你看下，能满足你需求不，vue-vben-admin这个，我们现在也有用到这个，如下图
![3212](https://user-images.githubusercontent.com/5857640/147537596-6cb36107-fe3f-4da5-80e3-1503500334ec.png)
![411](https://user-images.githubusercontent.com/5857640/147537714-a325e387-8fe8-4eb0-ab0c-b8b5763bb035.png)
