### ISSUE TITLE
没找到background url 赋值的地方，是直接改数据库吗

### ISSUE THREAD

**Issue by nbit99** [feihua/zero-admin#24]
SysMenu struct {
		BackgroundUrl  string    `db:"background_url"`   // 后台地址
	}

**Comment by feihua** [comment]
正在完善

**Comment by feihua** [comment]
在新增菜单的弹框那里
![image](https://github.com/feihua/zero-admin/assets/5857640/ef9cea40-d2c4-46ee-a32e-c7262c7767e5)
