### ISSUE TITLE
大佬 项目很多地方调用的时候会提示field id is not set

### ISSUE THREAD

**Issue by codeanl** [feihua/zero-admin#29]
大佬，我测试了好几个地方都存在field id is not set的情况，比如在会员管理删除会员的时候调用会提示
<img width="692" alt="截屏2023-06-12 10 45 32" src="https://github.com/feihua/zero-admin/assets/84824883/2e92bc15-176b-4313-830e-3d716f8ab081">
然后我在postman里面测试用id传是成功的
<img width="583" alt="截屏2023-06-12 10 45 56" src="https://github.com/feihua/zero-admin/assets/84824883/da65ae87-7f87-4dae-b144-5eaae7bb30fd">

**Comment by feihua** [comment]
单条记录删除和批量删除的问题。已修复
