### ISSUE TITLE
大佬 还是好多地方提示field brandId is not set

### ISSUE THREAD

**Issue by codeanl** [feihua/zero-admin#30]
会员地址update
商品列表add update
退货列表update
订单列表update delete
<img width="653" alt="截屏2023-06-12 21 01 21" src="https://github.com/feihua/zero-admin/assets/84824883/6ae43f5d-6fbd-47a3-8da6-3664d0759ad7">

还有会员地址的编辑按钮没有弹出编辑栏

**Comment by feihua** [comment]
商品列表add update
退货列表update
订单列表update delete
这个还在弄

还有会员地址的编辑按钮没有弹出编辑栏
这个是移动端会员注册的，后台不能修改，到时会去掉那个按钮的

**Comment by codeanl** [comment]
嗷还有退出登录的功能

**Comment by feihua** [comment]
> 嗷还有退出登录的功能

登录的暂时前端修复了

**Comment by feihua** [comment]
> 会员地址update 商品列表add update 退货列表update 订单列表update delete <img alt="截屏2023-06-12 21 01 21" width="653" src="https://user-images.githubusercontent.com/84824883/245151628-6ae43f5d-6fbd-47a3-8da6-3664d0759ad7.png">
> 
> 还有会员地址的编辑按钮没有弹出编辑栏

已修复
