### ISSUE TITLE
项目本地启动和二次开发

### ISSUE THREAD

**Issue by xuhande** [feihua/zero-admin#41]
Hi，这个项目本地启动和二次开发学习文档没那么清晰

**Comment by xuhande** [comment]
生成cmsrpc代码
没有找到rpc/props/props.proto，是否可以提供一下

**Comment by feihua** [comment]
> 生成cmsrpc代码
> 
> 没有找到rpc/props/props.proto，是否可以提供一下？
> 
> 
> 
> 缺少Redis数据，浏览时没有redis报错

截图看下

**Comment by feihua** [comment]
我代码没这个rpc/props/props.proto你自己加的不？

**Comment by xuhande** [comment]
对的，我就是在项目自己加了props学习一下逻辑，请问rpc intenal中的gen这些文件你是怎么生成的？

**Comment by feihua** [comment]
> 对的，我就是在项目自己加了props学习一下逻辑，请问rpc intenal中的gen这些文件你是怎么生成的？

rpc目录下model是用goctl model根据数据库表生成的，不过新版本现在切换成gorm。具体生成在每个服务下，例如sys下的gen目录就是根据gorm工具生产的

**Comment by xuhande** [comment]
已经生成成功了，好多bug，哈哈哈哈

新增用户和菜单后，请求后端失败。
切换新增用户登录，新用户没有菜单，请求失败。

{"@timestamp":"2024-05-23T22:05:32.960+08:00","caller":"serverinterceptors/statinterceptor.go:90","content":"192.168.0.100:61867 - /sysclient.SysLogService/SysLogAdd - {\"user_name\":\"abc\",\"operation\":\"POST\",\"method\":\"/api/sys/user/list\",\"request_params\":\"{\\\"current\\\":1,\\\"pageSize\\\":10}\",\"time\":7,\"ip\":\"127.0.0.1:49768\",\"response_params\":\"{\\\"code\\\":1001,\\\"message\\\":\\\"用户: abc,还没有登录,请先登录\\\"}\"}","duration":"26.1ms","level":"info","span":"3e133","trace":"405fef06f41e92cd32876d2ee423bff6"}
